// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace intelchat {

static const char* Chat_method_names[] = {
  "/intelchat.Chat/SendMsg",
};

std::unique_ptr< Chat::Stub> Chat::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Chat::Stub> stub(new Chat::Stub(channel));
  return stub;
}

Chat::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendMsg_(Chat_method_names[0], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::intelchat::Message, ::intelchat::Message>* Chat::Stub::SendMsgRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::intelchat::Message, ::intelchat::Message>::Create(channel_.get(), rpcmethod_SendMsg_, context);
}

void Chat::Stub::experimental_async::SendMsg(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::intelchat::Message,::intelchat::Message>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::intelchat::Message,::intelchat::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_SendMsg_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::intelchat::Message, ::intelchat::Message>* Chat::Stub::AsyncSendMsgRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::intelchat::Message, ::intelchat::Message>::Create(channel_.get(), cq, rpcmethod_SendMsg_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::intelchat::Message, ::intelchat::Message>* Chat::Stub::PrepareAsyncSendMsgRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::intelchat::Message, ::intelchat::Message>::Create(channel_.get(), cq, rpcmethod_SendMsg_, context, false, nullptr);
}

Chat::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Chat_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Chat::Service, ::intelchat::Message, ::intelchat::Message>(
          [](Chat::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::intelchat::Message,
             ::intelchat::Message>* stream) {
               return service->SendMsg(ctx, stream);
             }, this)));
}

Chat::Service::~Service() {
}

::grpc::Status Chat::Service::SendMsg(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::intelchat::Message, ::intelchat::Message>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace intelchat

